import 'dart:convert';

import 'package:crypto/crypto.dart';

import '../../data/models/member.dart';

/// The 3-key meeting unlock, mirrored from the backend's rule: a meeting
/// opens when **3 officials** (chairperson / secretary / treasurer) or
/// **5 members** have each confirmed their secret PIN. Groups smaller than
/// five can't reach the member quorum, so it caps at "everyone".
abstract final class MeetingUnlock {
  static const int officialsRequired = 3;
  static const int membersRequired = 5;

  /// Digits in a meeting PIN. Four, chosen by the member.
  ///
  /// It was six, generated by the server and sent by SMS. Four is a hundred
  /// times smaller a space — 10,000 rather than 1,000,000 — and a PIN somebody
  /// picks clusters far harder than a random one, so the two changes compound.
  /// [isGuessablePin] takes back some of that, and the quorum takes back more:
  /// opening a meeting needs three of these, not one.
  static const int pinLength = 4;

  /// The length PINs used to be. Verification still accepts one so a group
  /// whose members set a six-digit PIN before this change can still open a
  /// meeting; only setting a NEW pin requires four. Without this every
  /// existing group would be locked out of its own meetings by an app update.
  static const int legacyPinLength = 6;

  /// Hashes a PIN with a per-member salt so equal PINs don't hash equal.
  static String hashPin(String memberId, String pin) {
    return sha256.convert(utf8.encode('$memberId:${pin.trim()}')).toString();
  }

  static bool verifyPin(Member member, String pin) {
    final stored = member.pinHash;
    if (stored == null || stored.isEmpty) return false;
    return stored == hashPin(member.id, pin);
  }

  // `[0-9]` rather than `\d`: these patterns interpolate the length, so they
  // cannot be raw strings, and a backslash in an ordinary Dart string is one
  // more thing to get wrong.
  static final RegExp _setPattern = RegExp('^[0-9]{$pinLength}\$');
  static final RegExp _legacyPattern = RegExp('^[0-9]{$legacyPinLength}\$');

  /// A PIN a member may SET: exactly [pinLength] digits, 0-9, and not one of
  /// the handful anybody would try first.
  static bool isValidPin(String pin) {
    final value = pin.trim();
    return _setPattern.hasMatch(value) && !isGuessablePin(value);
  }

  /// A PIN a member may ENTER to turn their key. Accepts the old length too;
  /// see [legacyPinLength].
  static bool isEnterablePin(String pin) {
    final value = pin.trim();
    return _setPattern.hasMatch(value) || _legacyPattern.hasMatch(value);
  }

  /// PINs a keypad produces that nobody should be allowed to choose.
  ///
  /// This matters far more now the member picks their own than it did when the
  /// server generated one at random: left alone, a meaningful share of a group
  /// would hold 1234 or their year of birth, and three keys chosen that way are
  /// not three secrets.
  static bool isGuessablePin(String pin) {
    final value = pin.trim();
    if (value.length != pinLength) return false;
    // All the same digit, e.g. 0000. Deliberately not a regex: the first
    // attempt escaped the dollar, making it a LITERAL dollar sign rather
    // than end-of-string, so the pattern matched nothing and the check
    // silently did nothing at all.
    if (value.split('').toSet().length == 1) return true;
    // A run in either direction, e.g. 1234 or 4321.
    var ascending = true;
    var descending = true;
    for (var i = 1; i < value.length; i += 1) {
      final step = value.codeUnitAt(i) - value.codeUnitAt(i - 1);
      if (step != 1) ascending = false;
      if (step != -1) descending = false;
    }
    return ascending || descending;
  }

  static MeetingUnlockStatus evaluate({
    required List<Member> activeMembers,
    required Set<String> verifiedMemberIds,
  }) {
    final verified =
        activeMembers.where((m) => verifiedMemberIds.contains(m.id)).toList();
    final officialsVerified = verified.where((m) => m.isOfficial).length;
    final membersVerified = verified.length;
    final memberQuorum =
        activeMembers.length < membersRequired ? activeMembers.length : membersRequired;
    final satisfied = officialsVerified >= officialsRequired ||
        (memberQuorum > 0 && membersVerified >= memberQuorum);
    return MeetingUnlockStatus(
      officialsVerified: officialsVerified,
      membersVerified: membersVerified,
      officialsRequired: officialsRequired,
      memberQuorum: memberQuorum,
      satisfied: satisfied,
    );
  }
}

class MeetingUnlockStatus {
  const MeetingUnlockStatus({
    required this.officialsVerified,
    required this.membersVerified,
    required this.officialsRequired,
    required this.memberQuorum,
    required this.satisfied,
  });

  final int officialsVerified;
  final int membersVerified;
  final int officialsRequired;

  /// 5, or the whole group when it has fewer than 5 active members.
  final int memberQuorum;
  final bool satisfied;

  String get progressLabel =>
      '$officialsVerified of $officialsRequired officials · '
      '$membersVerified of $memberQuorum members';
}
