import 'dart:convert';
import 'dart:math';

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart';

import '../../data/models/member.dart';

/// The 3-key meeting unlock, mirrored from the backend's rule: a meeting
/// opens when **3 officials** (chairperson / secretary / treasurer) or
/// **5 members** have each confirmed their secret PIN. Groups smaller than
/// five can't reach the member quorum, so it caps at "everyone".
abstract final class MeetingUnlock {
  static const int officialsRequired = 3;
  static const int membersRequired = 5;

  /// Digits in a meeting PIN. Four, chosen by the member.
  ///
  /// It was six, generated by the server and sent by SMS. Four is a hundred
  /// times smaller a space — 10,000 rather than 1,000,000 — and a PIN somebody
  /// picks clusters far harder than a random one, so the two changes compound.
  /// [isGuessablePin] takes back some of that, and the quorum takes back more:
  /// opening a meeting needs three of these, not one.
  static const int pinLength = 4;

  /// The length PINs used to be. Verification still accepts one so a group
  /// whose members set a six-digit PIN before this change can still open a
  /// meeting; only setting a NEW pin requires four. Without this every
  /// existing group would be locked out of its own meetings by an app update.
  static const int legacyPinLength = 6;

  /// Work factor for [hashPin].
  ///
  /// A meeting PIN is four digits, so the whole keyspace is 10,000 values. The
  /// old scheme was a single SHA-256, which a laptop walks in milliseconds:
  /// anyone holding this phone's database file held every member's PIN, and
  /// those PINs are the three keys that open a meeting.
  ///
  /// 30,000 iterations turns that into ~3x10^8 HMAC operations for a full
  /// sweep. It also costs a fraction of a second on a low-end handset for the
  /// one hash a person's tap actually needs. It runs on the UI isolate, which
  /// is the reason for not going higher; moving it to `compute` would allow it.
  static const int _pbkdf2Iterations = 30000;

  /// Marks the algorithm in the stored value, so [verifyPin] can tell a new
  /// hash from a legacy one without guessing from its shape.
  static const String _pbkdf2Prefix = 'pbkdf2-sha256';

  /// Hashes a PIN with a random per-hash salt.
  ///
  /// Returns `pbkdf2-sha256$<iterations>$<salt>$<hash>`. The salt is random
  /// rather than the member id: a member id is not secret and is reused
  /// wherever that member appears, so it never forced an attacker to redo work.
  static String hashPin(String memberId, String pin, {String? salt}) {
    final saltValue = salt ?? _randomSalt();
    final derived = _pbkdf2(
      password: '$memberId:${pin.trim()}',
      salt: saltValue,
      iterations: _pbkdf2Iterations,
    );
    return '$_pbkdf2Prefix\$$_pbkdf2Iterations\$$saltValue\$$derived';
  }

  /// The scheme this replaced: one round of SHA-256, salted only by member id.
  ///
  /// Kept solely so a PIN set before the change still verifies. Anything that
  /// verifies this way should be re-hashed; see [needsRehash].
  static String legacyHashPin(String memberId, String pin) {
    return sha256.convert(utf8.encode('$memberId:${pin.trim()}')).toString();
  }

  /// True when [stored] is in the old format and should be upgraded after a
  /// successful verify. Upgrading on use is the only way to migrate: the PIN
  /// itself is never stored, so it can only be re-hashed at the moment someone
  /// types it correctly.
  static bool needsRehash(String? stored) =>
      stored != null && stored.isNotEmpty && !stored.startsWith('$_pbkdf2Prefix\$');

  static bool verifyPin(Member member, String pin) {
    final stored = member.pinHash;
    if (stored == null || stored.isEmpty) return false;

    if (!stored.startsWith('$_pbkdf2Prefix\$')) {
      return _constantTimeEquals(stored, legacyHashPin(member.id, pin));
    }

    final parts = stored.split('\$');
    if (parts.length != 4) return false;
    final iterations = int.tryParse(parts[1]);
    if (iterations == null || iterations <= 0) return false;

    final derived = _pbkdf2(
      password: '${member.id}:${pin.trim()}',
      salt: parts[2],
      iterations: iterations,
    );
    return _constantTimeEquals(parts[3], derived);
  }

  static String _randomSalt() {
    final random = Random.secure();
    final bytes = List<int>.generate(16, (_) => random.nextInt(256));
    return base64Url.encode(bytes).replaceAll('=', '');
  }

  /// PBKDF2-HMAC-SHA256. Written out rather than pulled from a package: it is
  /// twenty lines, and one fewer dependency in the path that guards a group's
  /// meetings is worth more than the twenty lines saved.
  static String _pbkdf2({
    required String password,
    required String salt,
    required int iterations,
    int lengthBytes = 32,
  }) {
    final hmac = Hmac(sha256, utf8.encode(password));
    final output = <int>[];
    var block = 1;

    while (output.length < lengthBytes) {
      // U1 = HMAC(password, salt || INT_32_BE(block))
      final blockSuffix = ByteData(4)..setUint32(0, block, Endian.big);
      var u = hmac
          .convert([...utf8.encode(salt), ...blockSuffix.buffer.asUint8List()])
          .bytes;
      final accumulated = List<int>.from(u);

      for (var i = 1; i < iterations; i += 1) {
        u = hmac.convert(u).bytes;
        for (var j = 0; j < accumulated.length; j += 1) {
          accumulated[j] ^= u[j];
        }
      }

      output.addAll(accumulated);
      block += 1;
    }

    return base64Url.encode(output.sublist(0, lengthBytes)).replaceAll('=', '');
  }

  /// Raw derived bytes as hex, so the hand-written KDF can be checked against
  /// published test vectors rather than only against itself.
  @visibleForTesting
  static String pbkdf2Hex({
    required String password,
    required String salt,
    required int iterations,
    int lengthBytes = 32,
  }) {
    final b64 = _pbkdf2(
      password: password,
      salt: salt,
      iterations: iterations,
      lengthBytes: lengthBytes,
    );
    final bytes = base64Url.decode(b64.padRight((b64.length + 3) ~/ 4 * 4, '='));
    return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }

  /// Compares without leaking where two values first differ.
  static bool _constantTimeEquals(String a, String b) {
    if (a.length != b.length) return false;
    var diff = 0;
    for (var i = 0; i < a.length; i += 1) {
      diff |= a.codeUnitAt(i) ^ b.codeUnitAt(i);
    }
    return diff == 0;
  }

  // `[0-9]` rather than `\d`: these patterns interpolate the length, so they
  // cannot be raw strings, and a backslash in an ordinary Dart string is one
  // more thing to get wrong.
  static final RegExp _setPattern = RegExp('^[0-9]{$pinLength}\$');
  static final RegExp _legacyPattern = RegExp('^[0-9]{$legacyPinLength}\$');

  /// A PIN a member may SET: exactly [pinLength] digits, 0-9, and not one of
  /// the handful anybody would try first.
  static bool isValidPin(String pin) {
    final value = pin.trim();
    return _setPattern.hasMatch(value) && !isGuessablePin(value);
  }

  /// A PIN a member may ENTER to turn their key. Accepts the old length too;
  /// see [legacyPinLength].
  static bool isEnterablePin(String pin) {
    final value = pin.trim();
    return _setPattern.hasMatch(value) || _legacyPattern.hasMatch(value);
  }

  /// PINs a keypad produces that nobody should be allowed to choose.
  ///
  /// This matters far more now the member picks their own than it did when the
  /// server generated one at random: left alone, a meaningful share of a group
  /// would hold 1234 or their year of birth, and three keys chosen that way are
  /// not three secrets.
  static bool isGuessablePin(String pin) {
    final value = pin.trim();
    if (value.length != pinLength) return false;
    // All the same digit, e.g. 0000. Deliberately not a regex: the first
    // attempt escaped the dollar, making it a LITERAL dollar sign rather
    // than end-of-string, so the pattern matched nothing and the check
    // silently did nothing at all.
    if (value.split('').toSet().length == 1) return true;
    // A run in either direction, e.g. 1234 or 4321.
    var ascending = true;
    var descending = true;
    for (var i = 1; i < value.length; i += 1) {
      final step = value.codeUnitAt(i) - value.codeUnitAt(i - 1);
      if (step != 1) ascending = false;
      if (step != -1) descending = false;
    }
    return ascending || descending;
  }

  static MeetingUnlockStatus evaluate({
    required List<Member> activeMembers,
    required Set<String> verifiedMemberIds,
  }) {
    final verified =
        activeMembers.where((m) => verifiedMemberIds.contains(m.id)).toList();
    final officialsVerified = verified.where((m) => m.isOfficial).length;
    final membersVerified = verified.length;
    final memberQuorum =
        activeMembers.length < membersRequired ? activeMembers.length : membersRequired;
    final satisfied = officialsVerified >= officialsRequired ||
        (memberQuorum > 0 && membersVerified >= memberQuorum);
    return MeetingUnlockStatus(
      officialsVerified: officialsVerified,
      membersVerified: membersVerified,
      officialsRequired: officialsRequired,
      memberQuorum: memberQuorum,
      satisfied: satisfied,
    );
  }
}

class MeetingUnlockStatus {
  const MeetingUnlockStatus({
    required this.officialsVerified,
    required this.membersVerified,
    required this.officialsRequired,
    required this.memberQuorum,
    required this.satisfied,
  });

  final int officialsVerified;
  final int membersVerified;
  final int officialsRequired;

  /// 5, or the whole group when it has fewer than 5 active members.
  final int memberQuorum;
  final bool satisfied;

  String get progressLabel =>
      '$officialsVerified of $officialsRequired officials · '
      '$membersVerified of $memberQuorum members';
}
