import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../core/database/app_database.dart';
import '../../core/theme/app_colors.dart';
import '../../core/utils/formatters.dart';
import '../../data/models/group.dart';
import '../../data/models/loan.dart';
import '../../data/models/member.dart';
import '../../data/repositories/loan_repository.dart';
import '../../data/repositories/member_repository.dart';
import '../../data/models/remote/member_passbook.dart';
import '../../data/services/member_matching.dart';
import '../../providers/app_state.dart';
import '../../providers/connection_provider.dart';
import '../../shared/widgets/common.dart';
import '../../shared/widgets/status_chip.dart';
import 'pdf_report.dart';
import 'report_share.dart';

/// A member's report generated BY THE GROUP from this phone's records —
/// savings, contributions, attendance and loans. Share it as text or hand
/// the member a proper PDF statement. Works fully offline.
class MemberReportLocalScreen extends StatefulWidget {
  const MemberReportLocalScreen({super.key, required this.memberId});

  final String memberId;

  @override
  State<MemberReportLocalScreen> createState() =>
      _MemberReportLocalScreenState();
}

class _MemberReportLocalScreenState extends State<MemberReportLocalScreen> {
  final _memberRepository = MemberRepository(AppDatabase.instance);
  final _loanRepository = LoanRepository(AppDatabase.instance);

  bool _loading = true;
  MemberFinancials? _financials;
  double _social = 0;
  double _fines = 0;
  double _attendanceRate = 0;
  List<Loan> _loans = const [];
  bool _sharing = false;

  /// The server's totals for this member, when we could reach them and be
  /// certain which member they belong to.
  MemberPassbook? _passbook;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) => _load());
  }

  Future<void> _load() async {
    final group = context.read<AppState>().group;
    if (group == null) {
      setState(() => _loading = false);
      return;
    }
    final all = await _memberRepository.financialsForGroup(group.id);
    final financials =
        all.where((f) => f.member.id == widget.memberId).firstOrNull;
    final contributions =
        await _memberRepository.contributionTotals(widget.memberId);
    final attendance =
        await _memberRepository.attendanceRate(widget.memberId);
    final loans = await _loanRepository.loansForMember(widget.memberId);

    // Members added on this handset carry a local id the server has never
    // seen, so cross over by phone — and only when it is unambiguous.
    if (!mounted) return;
    final connection = context.read<ConnectionProvider>();
    final remote = matchRemoteMember(financials?.member.phone, connection.members);
    final passbook =
        remote != null ? await connection.api.memberReport(remote.id) : null;

    if (!mounted) return;
    setState(() {
      _passbook = passbook;
      _financials = financials;
      _social = contributions.social;
      _fines = contributions.fines;
      _attendanceRate = attendance;
      _loans = loans;
      _loading = false;
    });
  }

  /// Server figures when we have them and know they are this member's,
  /// otherwise what this phone holds. One source per figure, used everywhere.
  double _savingsOf(MemberFinancials f) {
    final book = _passbook;
    return book != null ? book.shares + book.social : f.totalSavings;
  }

  double get _socialOf => _passbook?.social ?? _social;
  double get _finesOf => _passbook?.fines ?? _fines;
  double get _attendanceOf => _passbook?.attendanceRate ?? _attendanceRate;

  double _owedOf(MemberFinancials f) =>
      _passbook?.loanOutstanding ?? f.activeLoanBalance;

  bool get _fromServer => _passbook != null;

  String _buildReportText(Group group, MemberFinancials f) {
    final lines = <String>[
      'MEMBER REPORT — ${f.member.name}',
      '${group.name} · ${Formatters.fullDate(DateTime.now())}',
      '',
      reportLine('Role', f.member.role.label),
      reportLine('Joined', Formatters.shortDate(f.member.joinedAt)),
      '',
      'SAVINGS & CONTRIBUTIONS',
      reportLine('Total savings', Formatters.money(_savingsOf(f))),
      reportLine('Shares held', '${f.totalShares}'),
      reportLine('Social fund', Formatters.money(_socialOf)),
      reportLine('Fines paid', Formatters.money(_finesOf)),
      reportLine('Attendance', '${(_attendanceOf * 100).round()}%'),
      '',
      'LOANS (${_loans.length})',
    ];
    if (_loans.isEmpty) {
      lines.add('No loans taken.');
    }
    for (final loan in _loans) {
      lines.add('${Formatters.shortDate(loan.disbursedAt)} — '
          '${Formatters.money(loan.principal)}, '
          'repaid ${Formatters.money(loan.amountRepaid)} '
          '(${loan.status.label})');
    }
    if (_owedOf(f) > 0) {
      lines
        ..add('')
        ..add(reportLine('Still owed', Formatters.money(_owedOf(f))));
    }
    lines
      ..add('')
      ..add(_fromServer
          ? 'Figures confirmed by the IntelliCash server.'
          : 'Figures from this phone only - records saved elsewhere may not be '
              'included yet.')
      ..add('Shared from IntelliCash');
    return lines.join('\n');
  }

  Future<void> _shareText(Group group, MemberFinancials f) async {
    await shareReport(
        'Member Report — ${f.member.name}', _buildReportText(group, f));
  }

  Future<void> _sharePdf(Group group, MemberFinancials f) async {
    setState(() => _sharing = true);
    try {
      await shareMemberPdf(
        group: group,
        member: f.member,
        totalSavings: _savingsOf(f),
        totalShares: f.totalShares,
        socialContributions: _socialOf,
        finesPaid: _finesOf,
        activeLoanBalance: _owedOf(f),
        attendanceRate: _attendanceOf,
        loans: _loans,
      );
    } catch (_) {
      if (mounted) {
        showAppSnack(context, 'Could not create the PDF. Try again.',
            error: true);
      }
    } finally {
      if (mounted) setState(() => _sharing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final group = context.watch<AppState>().group;
    final f = _financials;

    return Scaffold(
      appBar: AppBar(title: const Text('Member Report')),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : (group == null || f == null)
              ? const EmptyState(
                  icon: Icons.person_outline,
                  title: 'Member not found',
                  message: 'This member is no longer in the group.',
                )
              : ListView(
                  padding: const EdgeInsets.fromLTRB(20, 8, 20, 24),
                  children: [
                    Row(
                      children: [
                        MemberAvatar(f.member.name, radius: 24),
                        const SizedBox(width: 12),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(f.member.name,
                                  style: Theme.of(context)
                                      .textTheme
                                      .titleMedium),
                              Text(
                                '${f.member.role.label} · joined '
                                '${Formatters.shortDate(f.member.joinedAt)}',
                                style:
                                    Theme.of(context).textTheme.bodySmall,
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                    const SectionLabel('Savings & contributions'),
                    Card(
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 15, vertical: 12),
                        child: Column(
                          children: [
                            KeyValueRow('Total savings',
                                Formatters.money(_savingsOf(f)),
                                emphasize: true),
                            KeyValueRow('Shares held', '${f.totalShares}'),
                            KeyValueRow(
                                'Social fund', Formatters.money(_socialOf)),
                            KeyValueRow(
                                'Fines paid', Formatters.money(_finesOf)),
                            KeyValueRow('Attendance',
                                '${(_attendanceOf * 100).round()}%'),
                          ],
                        ),
                      ),
                    ),
                    SectionLabel('Loans (${_loans.length})'),
                    if (_loans.isEmpty)
                      const EmptyState(
                        icon: Icons.payments_outlined,
                        title: 'No loans taken',
                        message: 'Loans this member takes will appear here.',
                      )
                    else
                      Card(
                        child: Padding(
                          padding: const EdgeInsets.symmetric(
                              horizontal: 15, vertical: 8),
                          child: Column(
                            children: [
                              for (final loan in _loans)
                                Padding(
                                  padding: const EdgeInsets.symmetric(
                                      vertical: 5),
                                  child: Row(
                                    children: [
                                      Expanded(
                                        child: Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              Formatters.money(
                                                  loan.principal),
                                              style: const TextStyle(
                                                  fontSize: 12.5,
                                                  fontWeight:
                                                      FontWeight.w600),
                                            ),
                                            Text(
                                              'Taken ${Formatters.shortDate(loan.disbursedAt)} · '
                                              'repaid ${Formatters.moneyCompact(loan.amountRepaid)}',
                                              style: TextStyle(
                                                  fontSize: 11,
                                                  color: AppColors
                                                      .textSecondary),
                                            ),
                                          ],
                                        ),
                                      ),
                                      StatusChip.loan(loan.status),
                                    ],
                                  ),
                                ),
                            ],
                          ),
                        ),
                      ),
                    if (_owedOf(f) > 0) ...[
                      const SizedBox(height: 8),
                      Card(
                        color: AppColors.pendingTint,
                        child: Padding(
                          padding: const EdgeInsets.all(14),
                          child: KeyValueRow('Still owed',
                              Formatters.money(_owedOf(f)),
                              emphasize: true),
                        ),
                      ),
                    ],
                  ],
                ),
      bottomNavigationBar: _loading || group == null || f == null
          ? null
          : SafeArea(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 8, 20, 16),
                child: Row(
                  children: [
                    Expanded(
                      child: OutlinedButton.icon(
                        onPressed: () => _shareText(group, f),
                        icon: const Icon(Icons.share, size: 18),
                        label: const Text('Share Text'),
                      ),
                    ),
                    const SizedBox(width: 10),
                    Expanded(
                      child: FilledButton.icon(
                        onPressed:
                            _sharing ? null : () => _sharePdf(group, f),
                        icon: const Icon(Icons.picture_as_pdf_outlined,
                            size: 18),
                        label: Text(_sharing ? 'Creating…' : 'Save PDF'),
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
